<?=$this->doctype()?>

<html>

<head>
	<?=$this->headTitle("##Site Title##")?>
	<?=$this->headLink()?>
	<?=$this->headScript()		
		->prependFile($this->baseUrl("js/atp/jquery-ui-1.9.0.custom.min.js"))
		->prependFile($this->baseUrl("js/atp/jquery-1.8.2.js"))
	?>
	<?=$this->headMeta()?>
	<base href="<?=$this->baseUrl("")?>"/>
</head>

<body>
	<div id="page">
		<div id="page-header">
			<?=$this->partial('layout/page_header.phtml')?>
		</div>

		<div id="page-content">
			<?php echo $this->layout()->content; ?>
		</div>
		
		<div id="page-footer">
			<?=$this->partial('layout/page_footer.phtml')?>
		</div>
	</div>
	
	<?=$this->partial('shared/analytics.phtml')?>
</body>

</html>
