<?php $this->headScript()->appendFile($this->baseUrl("js/admin.js"))?>
<?php $this->headLink()->appendStylesheet($this->baseUrl("css/admin.css"))?>

<div id="admin-header">
	<h1><a href="<?=$this->baseurl("admin")?>">##Admin Title##</a></h1>
	<a id="logout-link" href="<?=$this->url(array(), 'adminLogout')?>">Logout</a>
	<span id="id-span">Hi <?=\ATP\Acl::currentUser()->name?>!</span>
	<ul id="admin-menu">
		<?php foreach(\ATP\Admin::modelsByCategory() as $category => $models) { ?>
			<li>
				<a href=""><?=$category?></a>
				<ul>
					<?php foreach($models as $model) { ?>
						<li>
							<a href="<?=$this->url(array('action' => 'list', 'model' => \ATP\Inflector::underscore($model), 'id'=>null), 'admin')?>">
								<?=\ATP\Inflector::titleize($model)?>
							</a>
						</li>
					<?php } ?>
				</ul>
			</li>
		<?php } ?>
	</ul>
</div>