<?php if($this->flash->hasMessages()) { ?>
	<?php foreach($this->flash->getMessages() as $message) { ?>
		<p class="message"><?=$message?></p>
	<?php } ?>
<?php } ?>

<h2>
	<?php if($this->object->id) { ?>
		Edit <?=\ATP\Inflector::singularize(\ATP\Inflector::titleize($this->model))?> - <?=$this->object->displayName()?>
	<?php } else { ?>
		Create New <?=\ATP\Inflector::singularize(\ATP\Inflector::titleize($this->model))?>
	<?php } ?>
</h2>

<div id="admin-tabs">
	<ul>
		<li><a href="#object-details-tab">Details</a></li>
		<?php if($this->object->id) { ?>
			<?php foreach($this->object->subObjectFields() as $singular => $plural) { ?>
				<li><a href="#<?=$plural?>-tab"><?=$plural?></a></li>
			<?php } ?>
			<?php foreach($this->object->relatedObjectFields() as $singular => $data) { ?>
				<?php $plural = \ATP\Inflector::pluralize($singular)?>
				<li><a href="#<?=$plural?>-tab"><?=$plural?></a></li>
			<?php } ?>
		<?php } ?>
	</ul>
	
	<div id="object-details-tab">
		<div class="admin-edit model-edit-form">
			<form method="post" enctype="multipart/form-data">
				<input type="hidden" name="id" value="<?=$this->object->id?>" />
				
				<div class="owner-field-list">
					<label class="acl_owner" for="acl_owner">Owner</label>
					<input type="hidden" name="acl_owner_id" value="<?=$this->object->aclOwner->id?>" />
					<span><?=$this->object->aclOwner->name?></span>
					
					<label class="acl_group" for="acl_group">Group</label>
					<input type="hidden" name="acl_group_id" value="<?=$this->object->aclGroup->id?>" />
					<span><?=$this->object->aclGroup->name?></span>

					<?php foreach($this->object->ownerFields() as $column => $table) { $columnUnderscore = \ATP\Inflector::underscore($column); ?>
						<label class="<?=$columnUnderscore?>" for="<?=$columnUnderscore?>"><?=$column?></label>
						<?=$this->partial('form/model_select.phtml', array('column' => $column, 'obj' => $this->object->$column))?>
						<a href="<?=$this->url(array('action' => 'edit', 'id' => $this->object->$column->id, 'model' => \ATP\Inflector::pluralize($columnUnderscore)), 'admin')?>">Edit <?=$column?></a>
					<?php } ?>
				</div>
				
				<?php foreach($this->object->dataColumns() as $column) { ?>
					<?=$this->partial('form/label.phtml', array('column' => $column))?>
					<div class="model-input">
						<?=$this->partial("form/{$this->object->adminFieldType($column)}.phtml", array('object' => $this->object, 'column' => $column))?>
					</div>
				<?php } ?>
				
				<label for="submit"></label>
				<div class="model-input">
					<input type="submit" class="model-save" name="submit" value="Save" />
				</div>		
			</form>
		</div>
	</div>
	
	<?php if($this->object->id) { ?>
		<?php foreach($this->object->subObjectFields() as $singular => $plural) { ?>
			<div id="<?=$plural?>-tab">
				<div class="admin-edit">
					<?php $field = lcfirst($singular) . 'List'?>
					<?=$this->partial('admin/model_list.phtml', array('objects' => $this->object->{$field}, 'delete' => false))?>
					Add <?=$singular?> <?=$this->partial('form/model_select.phtml', array('column' => "new_{$singular}", 'obj' => $this->object->{$field}->temp()))?>
				</div>
			</div>
		<?php } ?>
		<?php foreach($this->object->relatedObjectFields() as $singular => $data) { ?>
			<?php $plural = \ATP\Inflector::pluralize($singular)?>
			<div id="<?=$plural?>-tab">
				<div class="admin-edit">
					<?php $field = lcfirst($singular) . 'List'?>
					<?=$this->partial('admin/model_list.phtml', array('objects' => $this->object->{$field}, 'delete' => false))?>
					Add <?=$singular?> <?=$this->partial('form/model_select.phtml', array('column' => "blah", 'obj' => $this->object->{$field}->temp()))?>
				</div>
			</div>
		<?php } ?>
	<?php } ?>
</div>

<p class="admin-return">
	<a href="<?=$this->url(array('action' => 'list', 'model' => $this->model), 'admin', true)?>">Back to <?=\ATP\Inflector::titleize($this->model)?></a>
</p>