<p>
	<a class="model-new" href="<?=$this->url(array('action' => 'edit', 'model' => $this->objects->modelType(), 'id' => null), 'admin')?>">
		Create a new <?=\ATP\Inflector::singularize(\ATP\Inflector::titleize($this->objects->modelType()))?>
	</a>
</p>

<table class="admin-model-list">
	<thead>
		<tr>
			<?php foreach($this->objects->adminColumns() as $column) { ?>
				<td class="ui-widget-header ui-corner-all"><?=$column?></td>
			<?php } ?>
			<td class="ui-widget-header ui-corner-all" colspan=2>Actions</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->objects as $obj) { ?>
			<tr>
				<?php foreach($this->objects->adminColumns() as $column) { ?>
					<td><?=$obj->$column?></td>
				<?php } ?>
				
				<td class="button-cell">
					<a class="edit-link admin-list-button" href="<?=$this->url(array('action' => 'edit', 'id' => $obj->identity(), 'model' => $obj->modelType()), 'admin')?>">Edit</a>
				</td>
				<?php if($this->delete) { ?>
					<td class="button-cell">
						<a class="delete-link admin-list-button" href="<?=$this->url(array('action' => 'delete', 'id' => $obj->identity(), 'model' => $obj->modelType()), 'admin')?>">Delete</a>
					</td>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
</table>
